# Generated by Django 3.2.7 on 2021-11-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_application',
            name='nid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guest_application',
            name='tel_no',
            field=models.CharField(max_length=255),
        ),
    ]
