# Generated by Django 3.2.7 on 2021-11-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20211114_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_application',
            name='is_active',
            field=models.BooleanField(default='0'),
        ),
    ]
