# Generated by Django 3.2.7 on 2021-11-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_auto_20211115_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.guest_application'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.members_personalinfo'),
        ),
    ]
