# Generated by Django 3.2.7 on 2021-12-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='visitor_chat_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, unique=True)),
                ('is_read', models.BooleanField(default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.visitor_chat')),
            ],
        ),
    ]
