# Generated by Django 3.2.7 on 2021-12-22 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='visitor_chat_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_message', models.CharField(default='', max_length=1024)),
                ('encrypted_replay', models.CharField(blank=True, default='', max_length=1024)),
                ('encrypted_file_path', models.CharField(default='', max_length=255)),
                ('is_read', models.BooleanField(default='0')),
                ('replied_at', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='created_at')),
                ('posted_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.visitor_chat')),
            ],
        ),
        migrations.CreateModel(
            name='chat_keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_keypath', models.CharField(max_length=255)),
                ('privatekey_path', models.CharField(max_length=255)),
                ('pass_phrase', models.CharField(max_length=255)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Created_at')),
                ('visitor_chat_message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.visitor_chat_message')),
            ],
        ),
    ]
