# Generated by Django 3.2.7 on 2021-12-23 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_keys',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='visitor_chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='visitor_chat_message',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='created_at'),
        ),
    ]
