# Generated by Django 3.2.7 on 2021-12-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor_chat_message',
            name='message',
        ),
        migrations.AddField(
            model_name='visitor_chat_message',
            name='encrypted_file_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visitor_chat_message',
            name='encrypted_message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='chat_keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_keypath', models.CharField(max_length=255)),
                ('privatekey_path', models.CharField(max_length=255)),
                ('pass_phrase', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_chat_message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_app.visitor_chat_message')),
            ],
        ),
    ]
