# Generated by Django 3.2.7 on 2021-12-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0002_auto_20211221_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_chat_message',
            name='encrypted_replay',
            field=models.CharField(default='', max_length=255),
        ),
    ]
