# Generated by Django 3.2.7 on 2021-12-23 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0003_auto_20211223_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_keys',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2021, 12, 23), verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='visitor_chat_message',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2021, 12, 23), verbose_name='created_at'),
        ),
    ]
