# Generated by Django 3.2.7 on 2021-12-24 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0005_auto_20211223_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_keys',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 3, 29, 16, 778050), verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='visitor_chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 3, 29, 16, 775070), verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='visitor_chat_message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 3, 29, 16, 777053), verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='visitor_chat_message',
            name='encrypted_file_path',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
